export const ROOT_HELP_TEXT_SECONDARY = [
  '  uncheck                   Uncheck a checkbox by --element ref',
  '  focus                     Focus an element by --element ref',
  '  clear                     Clear an input by --element ref',
  '  drag                      Drag --from ref to --to ref',
  '  upload                    Upload --files to a file input by --element ref',
  '  dblclick                  Double-click element by --element ref',
  '  forward                   Navigate forward in browser history',
  '  scrollintoview            Scroll --element into view',
  '  get                       Get element property (--what: text, html, value, url, title)',
  '  is                        Check element state (--what: visible, enabled, checked)',
  '  inserttext                Insert text without key events',
  '  mouse move                Move mouse to --x --y coordinates',
  '  mouse down                Press mouse button',
  '  mouse up                  Release mouse button',
  '  mouse wheel               Scroll wheel --dy [--dx]',
  '  find                      Find element by locator (--locator role|text|label --value <v>)',
  '  set device                Emulate device (--name "iPhone 12")',
  '  set offline               Toggle offline mode (--state on|off)',
  '  set headers               Set HTTP headers (--headers \'{"key":"val"}\')',
  '  set credentials           Set HTTP auth (--user <u> --pass <p>)',
  '  set media                 Set color scheme (--color-scheme dark|light)',
  '  clipboard read            Read clipboard contents',
  '  clipboard write           Write --text to clipboard',
  '  dialog accept             Accept browser dialog (--text for prompt response)',
  '  dialog dismiss            Dismiss browser dialog',
  '  storage local get         Get localStorage value by --key',
  '  storage local set         Set localStorage --key --value',
  '  storage local clear       Clear localStorage',
  '  storage session get       Get sessionStorage value by --key',
  '  storage session set       Set sessionStorage --key --value',
  '  storage session clear     Clear sessionStorage',
  '  download                  Download file via --selector to --path',
  '  highlight                 Highlight --selector on page',
  '  exec                      Run any agent-browser command (--command "...")',
  '',
  'Common Commands:',
  '  h0x open [--json]',
  '  h0x serve [--port <port>] [--pairing-address <host>] [--mobile-pairing] [--no-pairing] [--project-root <path>] [--recipe-json] [--json]',
  '  h0x status [--json]',
  '  h0x diagnostics memory [--json]',
  '  h0x agent-context [--json]',
  '  h0x account add [--agent claude|codex] [--json]',
  '  h0x account list [--json]',
  '  h0x host list [--json]',
  '  h0x environment add --name <name> --pairing-code <code> [--json]',
  '  h0x environment list [--json]',
  '  h0x environment show --environment <selector> [--json]',
  '  h0x environment rm --environment <selector> [--json]',
  '  h0x worktree list [--repo <selector>] [--limit <n>] [--json]',
  '  h0x worktree create --name <name> [--repo <selector>|--project <id> [--host <host-id>]|--project-host-setup <id>] [--agent <id>] [--prompt <text>] [--setup run|skip|inherit] [--base-branch <ref>] [--issue <number>] [--linear-issue <identifier-or-url>] [--comment <text>] [--parent-worktree <selector>] [--no-parent] [--run-hooks] [--activate] [--json]',
  '  h0x worktree show --worktree <selector> [--json]',
  '  h0x worktree current [--json]',
  '  h0x worktree set --worktree <selector> [--display-name <name>] [--issue <number|null>] [--linear-issue <identifier-or-url|null>] [--comment <text>] [--workspace-status <id>] [--parent-worktree <selector>|--no-parent] [--json]',
  '  h0x worktree rm --worktree <selector> [--force] [--run-hooks] [--json]',
  '  h0x worktree ps [--limit <n>] [--json]',
  '  h0x file open <path> [--worktree <selector>] [--json]',
  '  h0x file diff <path> [--staged] [--worktree <selector>] [--json]',
  '  h0x file open-changed [--mode edit|diff|both] [--worktree <selector>] [--json]',
  '  h0x terminal list [--worktree <selector>] [--limit <n>] [--include-visual-layouts] [--json]',
  '  h0x terminal show [--terminal <handle>] [--json]',
  '  h0x terminal read [--terminal <handle>] [--cursor <n>] [--limit <n>] [--json]',
  '  h0x terminal send [--terminal <handle>] [--text <text>] [--enter] [--interrupt] [--json]',
  '  h0x terminal wait [--terminal <handle>] --for exit|tui-idle [--timeout-ms <ms>] [--json]',
  '  h0x terminal create [--worktree <selector>] [--title <name>] [--command <text>] [--focus] [--json]',
  '  h0x terminal split [--terminal <handle>] [--direction horizontal|vertical] [--json]',
  '  h0x terminal switch [--terminal <handle>] [--json]',
  '  h0x terminal close ([--terminal <handle>] [--tab] | --worktree <selector> --all) [--json]',
  '  h0x project list [--json]',
  '  h0x project setups [--project <id>] [--host <host-id>] [--json]',
  '  h0x project setup-existing-folder --project <id> --host <host-id> --path <path> [--kind git|folder] [--display-name <name>] [--json]',
  '  h0x project setup-clone --project <id> --host <host-id> --url <clone-url> --destination <path> [--display-name <name>] [--json]',
  '  h0x project setup-create --project <id> --host <host-id> [--setup-id <id>] [--path <path>] [--kind git|folder] [--display-name <name>] [--worktree-base-path <path>] [--git-username <name>] [--state ready|not-set-up|setting-up|error|unsupported] [--method imported-existing-folder|cloned|provisioned] [--json]',
  '  h0x project setup-update --setup <setup-id> [--display-name <name>] [--path <path>] [--worktree-base-path <path>] [--git-username <name>] [--kind git|folder] [--state ready|not-set-up|setting-up|error|unsupported] [--method legacy-repo|imported-existing-folder|cloned|provisioned] [--json]',
  '  h0x project setup-delete --setup <setup-id> [--json]',
  '  h0x repo list [--json]',
  '  h0x repo add --path <path> [--json]',
  '  h0x repo show --repo <selector> [--json]',
  '  h0x repo set-base-ref --repo <selector> --ref <ref> [--json]',
  '  h0x repo search-refs --repo <selector> --query <text> [--limit <n>] [--json]',
  '',
  'Selectors:',
  '  --repo <selector>         Registered repo selector such as id:<id>, name:<name>, or path:<path>',
  '  --worktree <selector>     Worktree selector such as identity:<identity>, id:<repo-id>::<path>, name:<displayName>, branch:<branch>, issue:<number>, path:<path>, or active/current',
  '  --terminal <handle>       Runtime-issued terminal handle returned by `h0x terminal list --json`',
  '  --parent-worktree <selector> Parent worktree selector such as identity:<identity>, id:<repo-id>::<path>, branch:<branch>, issue:<number>, path:<path>, or active/current',
  '  --no-parent               Force no parent lineage for unrelated worktree creation/update',
  '',
  'Terminal Send Options:',
  '  --text <text>             Text to send to the terminal',
  '  --enter                   Append Enter after sending text',
  '  --interrupt               Send as an interrupt-style input when supported',
  '',
  'Terminal List Options:',
  '  --include-visual-layouts  Include tab and pane topology in JSON output',
  '',
  'Wait Options:',
  '  --for exit                Wait until the target terminal exits',
  '  --timeout-ms <ms>         Maximum wait time before timing out',
  '',
  'Output Options:',
  '  --json                    Emit machine-readable JSON instead of human text',
  '  --pairing-code <code>      Connect to a remote h0x-ADE runtime using a pavii-h0x://pair?... code',
  '  --environment <selector>   Connect using a saved environment id or name',
  '  --help                    Show this help message',
  '',
  'Behavior:',
  '  Most commands require a running h0x-ADE runtime. If h0x-ADE is not open yet, run `h0x open` first.',
  '  Remote runtime access can also be supplied with ORCA_PAIRING_CODE or ORCA_ENVIRONMENT.',
  '  Use selectors for discovery and handles for repeated live terminal operations.',
  '',
  'Agent Sessions And Worktrees:',
  '  `worktree create --agent` creates a new checkout with an agent.',
  '  To start a fresh agent in the current worktree, use:',
  '    h0x terminal create --worktree active --command "codex"',
  '',
  'Browser Workflow:',
  '  1. Create or navigate:  h0x tab create --url https://example.com',
  '                          h0x goto --url https://example.com',
  '  2. Inspect the page:    h0x snapshot',
  '     (Returns an accessibility tree with element refs like e1, e2, e3)',
  '     For concurrent workflows, prefer: h0x tab list --json',
  '     then reuse tabs[].browserPageId with --page <id> on later commands.',
  '  3. Interact:            h0x click --element e2',
  '                          h0x fill --element e5 --value "search query"',
  '                          h0x keypress --key Enter',
  '  4. Re-inspect:          h0x snapshot',
  '     (Element refs change after navigation — always re-snapshot before interacting)',
  '',
  'Browser Options:',
  '  --element <ref>           Element ref from snapshot (e.g. @e3)',
  '  --url <url>               URL to navigate to',
  '  --value <text>            Value to fill or select',
  '  --input <text>            Text to type at current focus (no element needed)',
  '  --expression <js>         JavaScript expression to evaluate',
  '  --key <key>               Key to press (Enter, Tab, Escape, Control+a, etc.)',
  '  --direction <dir>         Scroll direction: up or down',
  '  --amount <pixels>         Scroll distance in pixels (default: viewport height)',
  '  --index <n>               Tab index (from `tab list`)',
  '  --page <id>               Stable browser page id (preferred for concurrent workflows)',
  '  --profile <id>            Browser profile id',
  "  --show-profile            Include the tab's browser profile in text output",
  "  --no-ua-spoof             Keep Electron's native user agent for a new profile",
  '  --format <png|jpeg>       Screenshot image format',
  '  --from <ref>              Drag source element ref',
  '  --to <ref>                Drag target element ref',
  '  --files <path,...>        Comma-separated file paths for upload',
  '  --timeout <ms>            Wait timeout in milliseconds',
  "  --worktree <selector>     Scope commands to a specific worktree's browser tabs",
  '',
  'Examples:',
  '  $ h0x open',
  '  $ h0x status --json',
  '  $ h0x diagnostics memory --json',
  '  $ h0x repo list',
  '  $ h0x worktree create --name agent-task --agent codex --prompt "hi"',
  '  $ h0x worktree create --repo name:orca --name cli-test-1 --issue 273',
  '  $ h0x worktree create --repo name:orca --name linear-task --linear-issue https://linear.app/stably/issue/STA-335/test-issue',
  '  $ h0x worktree create --name linear-task --linear-issue STA-335',
  '  $ h0x worktree show --worktree branch:Jinwoo-H/cli',
  '  $ h0x worktree current',
  '  $ h0x worktree set --worktree active --comment "waiting on review"',
  '  $ h0x worktree set --worktree active --linear-issue null',
  '  $ h0x worktree ps --limit 10',
  '  $ h0x file open-changed --mode diff',
  '  $ h0x file open src/App.tsx',
  '  $ h0x terminal create --worktree active --command "codex"',
  '  $ h0x terminal list --worktree path:/Users/me/orca/workspaces/orca/cli-test-1 --json',
  '  $ h0x terminal send --terminal term_123 --text "hi" --enter',
  '  $ h0x terminal wait --terminal term_123 --for exit --timeout-ms 60000 --json',
  '  $ h0x tab current --json',
  '  $ h0x tab show --page page_123 --json',
  '  $ h0x tab create --url https://example.com --profile work',
  '  $ h0x tab profile clone --page page_123 --profile work --json',
  '  $ h0x snapshot',
  '  $ h0x click --element e3',
  '  $ h0x fill --element e5 --value "hello"',
  '  $ h0x goto --url https://example.com/login',
  '  $ h0x keypress --key Enter',
  '  $ h0x eval --expression "document.title"',
  '  $ h0x tab list --json'
].join('\n')
